# Generated by Django 3.2.6 on 2021-09-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_result_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='search',
        ),
        migrations.AddField(
            model_name='result',
            name='duration',
            field=models.CharField(default='duration', max_length=20),
            preserve_default=False,
        ),
    ]
